autoInstallPeers: true

catalogMode: manual

cleanupUnusedCatalogs: true

dedupeDirectDeps: true

optimisticRepeatInstall: true

resolvePeersFromWorkspaceRoot: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@effect/platform-node@4.0.0-beta.66'
  - '@effect/platform-node-shared@4.0.0-beta.66'
  - '@effect/vitest@4.0.0-beta.66'
  - effect@4.0.0-beta.66

packages:
  - apps/*
  - libs/*

catalog:
  '@antfu/eslint-config': ^9.0.0
  '@commitlint/cli': ^21.0.1
  '@commitlint/config-conventional': ^21.0.1
  '@effect/platform-node': 4.0.0-beta.66
  '@effect/tsgo': ^0.7.0
  '@effect/vitest': 4.0.0-beta.66
  '@types/node': ^25.6.0
  '@typescript/native-preview': 7.0.0-dev.20260513.1
  effect: 4.0.0-beta.66
  eslint: ^10.3.0
  husky: ^9.1.7
  knip: ^6.12.0
  lint-staged: ^17.0.2
  taze: ^19.11.0
  tsdown: ^0.22.0
  turbo: ^2.9.9
  typescript: ^6.0.3
  vitest: ^4.1.5
  yaml: ^2.9.0

updateConfig:
  ignoreDependencies:
    - typescript

verifyDepsBeforeRun: error
